export const MAXIMUM_TICKET_COUNT_IN_QUEUE = 5;
export const TIME_INTERVAL_TO_SEND_TICKETS = 1000 * 5;
export const DEVICE_ID_KEY = "d_id";
export const DEVICE_ID_INITIALIZED_KEY = "d_id_i";
export const SESSION_ID_KEY = "s_id";
export const SESSION_ID_INITIALIZED_KEY = "s_id_i";
export const SESSION_COUNT_KEY = "s_c";
export const USER_ID_KEY = "u_id";
export const TICKET_QUEUE_KEY = "a_q";
export const DEAD_LETTER_QUEUE_KEY = "d_a_q";
export const LIVE_SESSION_LENGTH = 1000 * 60 * 30;
export const MAXIMUM_RETRY_COUNT = 3;
export const DESTINATION_URL =
  "https://1cgir0gy5d.execute-api.us-east-1.amazonaws.com/prod/actionticket";

export type ActionTagType =
  | "pageView"
  | "authorShow"
  | "paperShow"
  | "refList"
  | "citedList"
  | "journalShow"
  | "query"
  | "downloadPdf"
  | "source"
  | "viewFullText"
  | "viewMorePDF"
  | "viewLessPDF"
  | "viewPDF"
  | "addToCollection"
  | "removeFromCollection"
  | "citePaper"
  | "signUpPopup"
  | "signInPopup"
  | "signUp"
  | "signIn"
  | "fos"
  | "copyDoi"
  | "signInViaCollection"
  | "blogPost"
  | "journalHomepage"
  | "authorEntityItem"
  | "paperSorting"
  | "collectionSharing"
  | "extendAbstract"
  | "collapseAbstract"
  | "PUBLISHED_YEAR"
  | "JOURNAL_IF"
  | "FOS"
  | "JOURNAL"
  | "applySavedFilter"
  | "applyPreviousFilter"
  | "addFilter"
  | "sendRequestLibraryLink"
  | "clickFindInLibraryBtn"
  | "journalSearch"
  | "fosSearch"
  | "collectionShow"
  | "addNote"
  | "removeNote"
  | "viewNote"
  | "sendRequestPaper"
  | "searchHistoryQuery"
  | "searchSuggestionQuery"
  | "blockUnsignedUser"
  | "blockUnverifiedUser"
  | "openSignUp"
  | "addToBookmark"
  | "authorFromSearch"
  | "doiSearch"
  | "signBannerAtSearch"
  | "signBannerAtPaperShow"
  | "relatedPaperAtPaperShow"
  | "bannerView"
  | "researchHistory"
  | "viewRelatedPaper"
  | "clickPagination"
  | "clickLogo"
  | "clickSignUpAtFirstForm"
  | "clickSignUpAtStep2"
  | "alertView"
  | "clickOk"
  | "childRefList"
  | "childCitedList"
  | "viewBasedOnCollectionPaper"
  | "viewBasedOnActivityPaper"
  | "clickSeeMore"
  | "clickSeeLess"
  | "clickGoToCollectionBtn"
  | "clickLetMeSeeBtn"
  | "clickNoThxBtn"
  | "viewKnowledgeBaseNoti"
  | "autoYearFilterQuery"
  | "cancelAutoYearFilter"
  | "clickPaperFigure"
  | "viewFigureList"
  | "clickPrevBtn"
  | "clickNextBtn"
  | "viewFigure"
  | "recommendEmailBanner"
  | "clickRefreshButton"
  | "savedCollection"
  | "clickViewCollection"
  | "clickCollectionTitle"
  | "clickCloseButton"
  | "viewCollectionSnackBar"
  | "createKeywordAlert"
  | "removeKeywordAlert"
  | "clickSeeAllBtn"
  | "viewCreateKeywordSnackbar"
  | "clickCreateAlertBtn"
  | "clickSubmitGSBtn"
  | "clickSubmitBibtexBtn"
  | "clickSubmitCitationStringBtn"
  | "clickSubmitAuthorUrlsBtn"
  | "declinedPaper"
  | "confirmedPaper"
  | "";

export type ActionArea = string;

export type PageType =
  | "profileShow"
  | "paperShow"
  | "authorShow"
  | "home"
  | "searchResult"
  | "authorSearchResult"
  | "journalShow"
  | "collectionShow"
  | "collectionList"
  | "signIn"
  | "signUp"
  | "resetPassword"
  | "emailVerification"
  | "terms"
  | "privacyPolicy"
  | "keywordSettingPage"
  | "unknown";
